openapi: 3.0.0
info:
  title: Shared Index
  version: v1
paths:
  /shared-index/config/matchkeys:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    post:
      description: Create match key.
      operationId: postMatchKey
      requestBody:
        content:
          application/json:
            schema:
              $ref: schemas/matchKey.json
      responses:
        "201":
          description: Created.
          content:
            application/json:
              schema:
                $ref: schemas/matchKey.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
    get:
      description: Get match keys.
      operationId: getMatchKeys
      parameters:
        - $ref: parameters/limit.yaml
        - $ref: parameters/query.yaml
        - $ref: parameters/offset.yaml
      responses:
        "200":
          description: list of match keys.
          content:
            application/json:
              schema:
                $ref: schemas/matchKeys.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /shared-index/config/matchkeys/{id}:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: match key identifier
        schema:
          type: string
    get:
      description: Get match key.
      operationId: getMatchKey
      responses:
        "200":
          description: Get match key.
          content:
            application/json:
              schema:
                $ref: schemas/matchKey.json
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    delete:
      description: Delete match key.
      operationId: deleteMatchKey
      responses:
        "204":
          description: deleted.
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
  /shared-index/sources:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    post:
      description: Create source.
      operationId: postSource
      requestBody:
        content:
          application/json:
            schema:
              $ref: schemas/source.json
      responses:
        "201":
          description: Created.
          content:
            application/json:
              schema:
                $ref: schemas/source.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
    get:
      description: Get sources.
      operationId: getSources
      parameters:
        - $ref: parameters/limit.yaml
        - $ref: parameters/query.yaml
        - $ref: parameters/offset.yaml
      responses:
        "200":
          description: list of sources.
          content:
            application/json:
              schema:
                $ref: schemas/sources.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /shared-index/config/sources/{id}:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: source identifier
        schema:
          type: string
          format: uuid
    get:
      description: Get source.
      operationId: getSource
      responses:
        "200":
          description: get match key.
          content:
            application/json:
              schema:
                $ref: schemas/matchKey.json
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    delete:
      description: Delete source.
      operationId: deleteSource
      responses:
        "204":
          description: deleted.
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
  /shared-index/shared-titles:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    get:
      description: Get shared titles.
      operationId: getSharedTitles
      parameters:
        - $ref: parameters/limit.yaml
        - $ref: parameters/query.yaml
        - $ref: parameters/offset.yaml
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: schemas/sharedTitles.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
    put:
      description: Enter a title for sharing.
      operationId: putSharedTitle
      requestBody:
        content:
          application/json:
            schema:
              $ref: schemas/sharedTitle.json
      responses:
        "204":
          description: OK
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
components:
  responses:
    trait_400:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid JSON in request
        application/json:
          schema:
            type: object
            example: {"error":"Invalid JSON in request"}
    trait_404:
      description: Not Found
      content:
        text/plain:
          schema:
            type: string
            example: Identifier 596d9f60-cda3-44d2-a4a1-2f48b7d4d23c not found
        application/json:
          schema:
            type: object
            example: {"error":"Identifier 596d9f60-cda3-44d2-a4a1-2f48b7d4d23c not found"}
    trait_500:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error, contact administrator
  schemas:
    errors:
      $ref: schemas/errors.json

